### ISSUE TITLE
Improve documentation with reference-site and improved docstrings

### ISSUE THREAD

**Issue by clbarnes** [Impelon/PyGVisuals#15]
... where?

**Comment by Impelon** [comment]
Well mostly the documentation consists of docstrings in the python code, [use-examples](https://github.com/Impelon/PyGVisuals/tree/python-3/pygvisuals/examples) and a rough (and slightly outdated) UML [here](https://htmlpreview.github.io/?https://github.com/Impelon/PyGVisuals/blob/python-3/GUI-System.class.violet.html) (which yes, I forgot to update the link in the readme, when I renamed branches).

While I agree that this kind of documentation is not very intuitive to use, I always find examples very helpful and I feel that the provided ones illustrate PyGVisuals capabilities good enough. 
Also keep in mind, that since all of the sourcecode is commented with docstrings, you can use the `help(...)`-function to print out that documentation while coding.

The "semantics" of the widgets are similar to those of Tk. 

I guess in retrospect it is not fair to call it _well_ documented, but it felt good enough at the time.

**Comment by clbarnes** [comment]
It's fairly easy to use [sphinx](https://www.sphinx-doc.org/en/master/) to autogenerate a documentation website from your docstrings and inheritance structure, which can be served by readthedocs or github.io automatically. I started on a branch but was having installation issues with the library, but it's worth looking into if you're interested in making the information more discoverable.

**Comment by Impelon** [comment]
Alright, that does sound great. Thanks for the tip.
I will look into that when I find the time!

**Comment by Impelon** [comment]
Closed by #17 
View the documentation on the new [homepage](https://impelon.github.io/PyGVisuals/)!

**Comment by clbarnes** [comment]
Awesome, looks great!
